### PR TITLE
Change The Plugins base-url

### PR DESCRIPTION
**Pull request by yJunS**

### CODE REVIEW

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
In order to build a new image, please modify the docker image tag bellow:
https://github.com/jenkins-zh/mirror-adapter/blob/c14bff355678579fdb5f8dec38ced35495c608d0/.github/workflows/maven.yml#L24

By the way, if you already have an image that allows other reviews to verify it please add a comment of it. If you don't have it, would you mind build it then push it to hub.docker.com? You can create a public repo on it so we can pull it.

**Comment by yJunS** [comment]
> In order to build a new image, please modify the docker image tag bellow:
> https://github.com/jenkins-zh/mirror-adapter/blob/c14bff355678579fdb5f8dec38ced35495c608d0/.github/workflows/maven.yml#L24
> 
> By the way, if you already have an image that allows other reviews to verify it please add a comment of it. If you don't have it, would you mind build it then push it to hub.docker.com? You can create a public repo on it so we can pull it.

I don’t have permission for that account, I can't push the docker images

**Comment by LinuxSuRen** [comment]
> I don’t have permission for that account, I can't push the docker images

I'm not requesting you push a test image into `docker.pkg.github.com/jenkins-zh/mirror-adapter/mirror-adapter`. Docker.hub allows everyone creates their own public repo.

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Comment by vsxen** [comment]
这个update的json也是分版本的吧？
我用目前的LTS 2.249.1 暴力替换URL，https://mirrors.ustc.edu.cn/jenkins/updates/dynamic-stable-2.249.1/update-center.json
然后用`python3 -m http.server`，jenkins报checksum不一致？
但是用旧的就可以。

**Comment by LinuxSuRen** [comment]
只是简单地替换肯定不行的，不然的话，你的Jenkins就太容易被钓鱼攻击了。

**Pull request merged**
